### ISSUE TITLE
[BUG] KeyError: 'game'

### ISSUE THREAD

**Issue by kiril22855** [dereklee0310/RussianFishing4Script#32]
C:\Users\drfan>cd C:\Users\drfan\Desktop\RussianFishing4Script-main\src

C:\Users\drfan\Desktop\RussianFishing4Script-main\src>python app.py
Traceback (most recent call last):
  File "C:\Users\drfan\Desktop\RussianFishing4Script-main\src\app.py", line 329, in <module>
    app = App()
          ^^^^^
  File "C:\Users\drfan\Desktop\RussianFishing4Script-main\src\app.py", line 78, in __init__
    self.setting = Setting()
                   ^^^^^^^^^
  File "C:\Users\drfan\Desktop\RussianFishing4Script-main\src\setting.py", line 105, in __init__
    self._merge_general_configs()
  File "C:\Users\drfan\Desktop\RussianFishing4Script-main\src\setting.py", line 114, in _merge_general_configs
    section = self.config["game"]
              ~~~~~~~~~~~^^^^^^^^
  File "C:\Users\drfan\AppData\Local\Programs\Python\Python311\Lib\configparser.py", line 979, in __getitem__
    raise KeyError(key)
KeyError: 'game'

**Comment by dereklee0310** [comment]
Please run `setup.bat` before using the main script

**Comment by kiril22855** [comment]
Thank :)
