### ISSUE TITLE
I cant understand what's wrong.

### ISSUE THREAD

**Issue by LoLuxe** [dereklee0310/RussianFishing4Script#39]
Hi, I'm bad at programming and I can't understand what's wrong here, can you help me?

INFO: Verifying file integrity

██████╗ ███████╗██╗  ██╗███████╗
██╔══██╗██╔════╝██║  ██║██╔════╝
██████╔╝█████╗  ███████║███████╗
██╔══██╗██╔══╝  ╚════██║╚════██║
██║  ██║██║          ██║███████║
╚═╝  ╚═╝╚═╝          ╚═╝╚══════╝
https://github.com/dereklee0310/RussianFishing4Script
+-----------------------------------------------+
| Welcome! Please select a profile id to use it |
+-----------------------------------------------+
|  0. edit configuration file                   |
|  1. spin_example                              |
|  2. spin_with_pause_example                   |
|  3. bottom_example                            |
|  4. marine_pirk_example                       |
|  5. marine_elevator_example                   |
|  6. float_example                             |
|  7. wakey_rig_example                         |
+-----------------------------------------------+
Enter profile id or press q to exit: 6
+------------------------------------------+
|                 Setings                  |
+--------------------------+---------------+
| Coffee drinking          | disabled      |
| Alcohol drinking         | disabled      |
| Player stat refill       | disabled      |
| Baits harvesting         | disabled      |
| Gear ratio switching     | disabled      |
| Plotting                 | disabled      |
| Shutdown                 | disabled      |
| Lifting                  | disabled      |
| Email sending            | disabled      |
| miaotixing sending       | disabled      |
| Result screenshot        | disabled      |
| Cast skipping            | disabled      |
| Friction brake changing  | disabled      |
| Spod rod recast          | disabled      |
| Lure changing            | disabled      |
| Mouse moving             | disabled      |
| Pause                    | disabled      |
| Bite screenshot          | disabled      |
| Unmarked release         | disabled      |
| Rainbow line             | disabled      |
| Fishes in keepnet        | 0             |
| Boat ticket duratioin    | None          |
+--------------------------+---------------+
| Profile name             | float_example |
| Fishing strategy         | float         |
| Cast power level         | 5.0           |
| Cast delay               | 4.0           |
| Enable post-acceleration | never         |
| Float confidence         | 0.68          |
| Check delay              | 1.0           |
| Pull delay               | 0.5           |
| Drifting timeout         | 16.0          |
+--------------------------+---------------+
Do you want to continue with the settings above? [Y/n] Y
INFO: Casting
INFO: Checking float status
Traceback (most recent call last):
  File "C:\Users\alexe\AppData\Local\Programs\Python\Python313\Lib\site-packages\pyautogui\__init__.py", line 172, in wrapper
    return wrappedFunction(*args, **kwargs)
  File "C:\Users\alexe\AppData\Local\Programs\Python\Python313\Lib\site-packages\pyautogui\__init__.py", line 210, in locateOnScreen
    return pyscreeze.locateOnScreen(*args, **kwargs)
           ~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "C:\Users\alexe\AppData\Local\Programs\Python\Python313\Lib\site-packages\pyscreeze\__init__.py", line 405, in locateOnScreen
    retVal = locate(image, screenshotIm, **kwargs)
  File "C:\Users\alexe\AppData\Local\Programs\Python\Python313\Lib\site-packages\pyscreeze\__init__.py", line 383, in locate
    points = tuple(locateAll(needleImage, haystackImage, **kwargs))
  File "C:\Users\alexe\AppData\Local\Programs\Python\Python313\Lib\site-packages\pyscreeze\__init__.py", line 257, in _locateAll_opencv
    raise ImageNotFoundException('Could not locate the image (highest confidence = %.3f)' % result.max())
pyscreeze.ImageNotFoundException: Could not locate the image (highest confidence = 0.480)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\alexe\Desktop\RussianFishing4Script-main\src\app.py", line 439, in <module>
    app.player.start_fishing()
    ~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\alexe\Desktop\RussianFishing4Script-main\src\player.py", line 122, in start_fishing
    self.float_fishing()
    ~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\alexe\Desktop\RussianFishing4Script-main\src\player.py", line 245, in float_fishing
    self._resetting_stage()
    ~~~~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\alexe\Desktop\RussianFishing4Script-main\src\script.py", line 216, in wrapper
    func(self, *args)
    ~~~~^^^^^^^^^^^^^
  File "C:\Users\alexe\Desktop\RussianFishing4Script-main\src\player.py", line 420, in _resetting_stage
    if self.monitor.is_tackle_ready():
       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\alexe\Desktop\RussianFishing4Script-main\src\monitor.py", line 114, in is_tackle_ready
    return self._locate_single_image_box("ready", 0.6)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^
  File "C:\Users\alexe\Desktop\RussianFishing4Script-main\src\monitor.py", line 48, in _locate_single_image_box
    return pag.locateOnScreen(
           ~~~~~~~~~~~~~~~~~~^
        f"{self.setting.image_dir}/{image}.png", confidence=confidence
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\alexe\AppData\Local\Programs\Python\Python313\Lib\site-packages\pyautogui\__init__.py", line 174, in wrapper
    raise ImageNotFoundException  # Raise PyAutoGUI's ImageNotFoundException.
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
pyautogui.ImageNotFoundException

**Comment by dereklee0310** [comment]
Seems like you are using a newer version of `pyautogui` or `pyscreeze` package, create a new virtual environment and do a fresh install or run `pip install --upgrade --force-reinstall -r requirements.txt` to downgrade packages, note that the latter one might break another project's dependices (if you have one).

**Comment by LoLuxe** [comment]
If I use this pip command, there will be another problem:
C:\Users\alexe\Desktop\RussianFishing4Script-main>pip install --upgrade --force-reinstall -r requirements.txt
Collecting pyautogui==0.9.54 (from -r requirements.txt (line 1))
  Using cached PyAutoGUI-0.9.54-py3-none-any.whl
Collecting keyboard==0.13.5 (from -r requirements.txt (line 2))
  Using cached keyboard-0.13.5-py3-none-any.whl.metadata (4.0 kB)
Collecting pywin32==307 (from -r requirements.txt (line 3))
  Using cached pywin32-307-cp313-cp313-win_amd64.whl.metadata (8.3 kB)
Collecting configparser==6.0.0 (from -r requirements.txt (line 4))
  Using cached configparser-6.0.0-py3-none-any.whl.metadata (11 kB)
Collecting pynput==1.7.6 (from -r requirements.txt (line 5))
  Using cached pynput-1.7.6-py2.py3-none-any.whl.metadata (30 kB)
Collecting opencv-python==4.8.0.76 (from -r requirements.txt (line 6))
  Using cached opencv_python-4.8.0.76-cp37-abi3-win_amd64.whl.metadata (20 kB)
Collecting Pillow==10.0.0 (from -r requirements.txt (line 7))
  Using cached Pillow-10.0.0.tar.gz (50.5 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error

  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [21 lines of output]
      Traceback (most recent call last):
        File "C:\Users\alexe\AppData\Local\Programs\Python\Python313\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 353, in <module>
          main()
          ~~~~^^
        File "C:\Users\alexe\AppData\Local\Programs\Python\Python313\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ~~~~^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\alexe\AppData\Local\Programs\Python\Python313\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
        File "C:\Users\alexe\AppData\Local\Temp\pip-build-env-85cvyp4o\overlay\Lib\site-packages\setuptools\build_meta.py", line 334, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=[])
                 ~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\alexe\AppData\Local\Temp\pip-build-env-85cvyp4o\overlay\Lib\site-packages\setuptools\build_meta.py", line 304, in _get_build_requires
          self.run_setup()
          ~~~~~~~~~~~~~~^^
        File "C:\Users\alexe\AppData\Local\Temp\pip-build-env-85cvyp4o\overlay\Lib\site-packages\setuptools\build_meta.py", line 320, in run_setup
          exec(code, locals())
          ~~~~^^^^^^^^^^^^^^^^
        File "<string>", line 30, in <module>
        File "<string>", line 27, in get_version
      KeyError: '__version__'
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.

-------------------------------------------

And if I change Pillow==10.0.0 to Pillow==11.0.0 then there will be:

Building wheels for collected packages: matplotlib
  Building wheel for matplotlib (pyproject.toml) ... error
  error: subprocess-exited-with-error

  × Building wheel for matplotlib (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [641 lines of output]
      WARNING setuptools_scm.pyproject_reading toml section missing 'pyproject.toml does not contain a tool.setuptools_scm section'
      Traceback (most recent call last):
        File "C:\Users\alexe\AppData\Local\Temp\pip-build-env-m62vsksb\overlay\Lib\site-packages\setuptools_scm\_integration\pyproject_reading.py", line 36, in read_pyproject
          section = defn.get("tool", {})[tool_name]
                    ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^
      KeyError: 'setuptools_scm'
      C:\Users\alexe\AppData\Local\Temp\pip-build-env-m62vsksb\overlay\Lib\site-packages\setuptools_scm\git.py:312: UserWarning: git archive did not support describe output
        warnings.warn("git archive did not support describe output")
      C:\Users\alexe\AppData\Local\Temp\pip-build-env-m62vsksb\overlay\Lib\site-packages\setuptools_scm\git.py:331: UserWarning: unprocessed git archival found (no export subst applied)
        warnings.warn("unprocessed git archival found (no export subst applied)")

      Edit mplsetup.cfg to change the build options; suppress output with --quiet.

      BUILDING MATPLOTLIB
            python: yes [3.13.0 (tags/v3.13.0:60403a5, Oct  7 2024, 09:38:07) [MSC
                        v.1941 64 bit (AMD64)]]
          platform: yes [win32]
             tests: no  [skipping due to configuration]
            macosx: no  [Mac OS-X only]
.
.
.
.
\afm
      copying lib\matplotlib\mpl-data\fonts\afm\ptmbi8a.afm -> build\lib.win-amd64-cpython-313\matplotlib\mpl-data\fonts\afm
      running build_ext
      Extracting /project/freetype/freetype2/2.6.1/freetype-2.6.1.tar.gz
      Building freetype in build\freetype-2.6.1
      error: Microsoft Visual C++ 14.0 or greater is required. Get it with "Microsoft C++ Build Tools": https://visualstudio.microsoft.com/visual-cpp-build-tools/
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for matplotlib
Failed to build matplotlib
ERROR: ERROR: Failed to build installable wheels for some pyproject.toml based projects (matplotlib)

**Comment by LoLuxe** [comment]
Collecting pyautogui==0.9.54 (from -r requirements.txt (line 1))
  Using cached PyAutoGUI-0.9.54-py3-none-any.whl
Collecting keyboard==0.13.5 (from -r requirements.txt (line 2))
  Using cached keyboard-0.13.5-py3-none-any.whl.metadata (4.0 kB)
ERROR: Could not find a version that satisfies the requirement pywin32==306 (from versions: 307, 308)
ERROR: No matching distribution found for pywin32==306

I think version of pywin32 isn't available for installation, so I chandeg it to 307 and saw this:
Collecting Pillow==10.0.0 (from -r requirements.txt (line 7))
  Using cached Pillow-10.0.0.tar.gz (50.5 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error

  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [21 lines of output]
      Traceback (most recent call last):
        File "C:\Users\alexe\rf4\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 353, in <module>
          main()
          ~~~~^^
        File "C:\Users\alexe\rf4\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ~~~~^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\alexe\rf4\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
        File "C:\Users\alexe\AppData\Local\Temp\pip-build-env-kn2mwap5\overlay\Lib\site-packages\setuptools\build_meta.py", line 334, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=[])
                 ~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\alexe\AppData\Local\Temp\pip-build-env-kn2mwap5\overlay\Lib\site-packages\setuptools\build_meta.py", line 304, in _get_build_requires
          self.run_setup()
          ~~~~~~~~~~~~~~^^
        File "C:\Users\alexe\AppData\Local\Temp\pip-build-env-kn2mwap5\overlay\Lib\site-packages\setuptools\build_meta.py", line 320, in run_setup
          exec(code, locals())
          ~~~~^^^^^^^^^^^^^^^^
        File "<string>", line 30, in <module>
        File "<string>", line 27, in get_version
      KeyError: '__version__'
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

so I changed Pillow to 11.0.0

and got a new problem:
Do you want to continue with the settings above? [Y/n] Y
Traceback (most recent call last):
  File "C:\Users\alexe\Desktop\rr4\src\app.py", line 439, in <module>
    app.player.start_fishing()
    ~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\alexe\Desktop\rr4\src\player.py", line 122, in start_fishing
    self.float_fishing()
    ~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\alexe\Desktop\rr4\src\player.py", line 245, in float_fishing
    self._resetting_stage()
    ~~~~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\alexe\Desktop\rr4\src\script.py", line 216, in wrapper
    func(self, *args)
    ~~~~^^^^^^^^^^^^^
  File "C:\Users\alexe\Desktop\rr4\src\player.py", line 420, in _resetting_stage
    if self.monitor.is_tackle_ready():
       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\alexe\Desktop\rr4\src\monitor.py", line 114, in is_tackle_ready
    return self._locate_single_image_box("ready", 0.6)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^
  File "C:\Users\alexe\Desktop\rr4\src\monitor.py", line 48, in _locate_single_image_box
    return pag.locateOnScreen(
           ~~~~~~~~~~~~~~~~~~^
        f"{self.setting.image_dir}/{image}.png", confidence=confidence
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\alexe\rf4\Lib\site-packages\pyautogui\__init__.py", line 172, in wrapper
    return wrappedFunction(*args, **kwargs)
  File "C:\Users\alexe\rf4\Lib\site-packages\pyautogui\__init__.py", line 210, in locateOnScreen
    return pyscreeze.locateOnScreen(*args, **kwargs)
           ~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "C:\Users\alexe\rf4\Lib\site-packages\pyscreeze\__init__.py", line 378, in locateOnScreen
    retVal = locate(image, screenshotIm, **kwargs)
  File "C:\Users\alexe\rf4\Lib\site-packages\pyscreeze\__init__.py", line 356, in locate
    points = tuple(locateAll(needleImage, haystackImage, **kwargs))
  File "C:\Users\alexe\rf4\Lib\site-packages\pyscreeze\__init__.py", line 247, in _locateAll_pillow
    raise NotImplementedError('The confidence keyword argument is only available if OpenCV is installed.')
NotImplementedError: The confidence keyword argument is only available if OpenCV is installed.

(rf4) C:\Users\alexe\Desktop\rr4\src>pip install opencv
ERROR: Could not find a version that satisfies the requirement opencv (from versions: none)
ERROR: No matching distribution found for opencv

(rf4) C:\Users\alexe\Desktop\rr4\src>pip install opencv-python==4.8.0.76
Requirement already satisfied: opencv-python==4.8.0.76 in c:\users\alexe\rf4\lib\site-packages (4.8.0.76)
Requirement already satisfied: numpy>=1.21.2 in c:\users\alexe\rf4\lib\site-packages (from opencv-python==4.8.0.76) (2.1.3)

**Comment by dereklee0310** [comment]
Some packages from older versions are used for compatibility, so using the latest Python version (3.13) could be buggy, and upgrading individual packages would also likely to break the dependencies.

Downgrade Python to 3.10 ~ 3.12 and install packages again should solve your problem.

**Comment by dereklee0310** [comment]
Closing due to inactivity.
